### ISSUE TITLE
提交完成表單的時候會出現資料不安全的提示，然後按仍要傳送後，並不會紀錄完成

### ISSUE THREAD

**Issue by TimHu950112** [Timothychen00/linebot1#5]
![Screenshot_2022-04-03-09-58-55-02](https://user-images.githubusercontent.com/94494969/161407973-0486ede1-f1f0-4611-859e-b58cb9d719e0.jpg)

**Comment by Timothychen00** [comment]
這個是因為非HTTPS請求被AZURE擋掉（因為azure的設定），目前已修復
